<?xml version="1.0" encoding="utf-8"?><Database Name="messageData" Class="messagesDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\messageData.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="messageDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.awMessages" Member="awMessages">
    <Type Name="awMessage">
      <Column Name="messageID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="messageText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="messageDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spRnd" Method="spRnd">
    <Parameter Name="P" Parameter="p" Type="System.Char" DbType="NChar(1)" />
    <ElementType Name="spRndResult">
      <Column Name="messageID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="messageText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="messageDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>